/*
 * File: app/store/FeelingsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.FeelingsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'FeelingsStore',
        fields: [
            {
                name: 'HappySadText'
            },
            {
                name: 'HappySadValue'
            },
            {
                name: 'BoredExcitedText'
            },
            {
                name: 'BoredExcitedValue'
            },
            {
                name: 'ScaredSafeText'
            },
            {
                name: 'ScaredSafeValue'
            },
            {
                name: 'AngryPeacefulText'
            },
            {
                name: 'AngryPeacefulValue'
            }
        ]
    }
});